FROM node:16

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN apt update -y && apt install xsel

COPY . .

EXPOSE 5000

RUN npm list

RUN npm run build && npm install -g serve

CMD ["serve", "-s", "-l", "5000", "build"]